New test for broke TpetraCrsMatrix%getGlobalRowView
Updated to latest SWIG. Currently fails to compile:

```
       call A%getGlobalRowView(gblrow, cgview(1:nnz), csview(1:nnz))
                                                                   1
Error: Type mismatch in argument 'indices' at (1); passed INTEGER(8) to CLASS(swigtype_teuchos__arrayviewt_long_long_const_t)
```